name: Clear Discord Channel

on:
  schedule:
    - cron: '03 10 * * *'  # 5:03 PM GMT+7
    - cron: '3 17 * * *'  # 12:03 AM GMT+7 (midnight)
  workflow_dispatch: # cho phép chạy thủ công

jobs:
  clear-channel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run clear script
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
        run: python clear_discord.py
